name: Rebuild Docker Image

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build -t postgres-ru:13 -f ./Dockerfile-13 . && docker tag postgres-ru:13 frozendevs/postgres-ru:13 

      - name: Login in DockerHub
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        run: docker push frozendevs/postgres-ru:13
